CREATE DATABASE SistemaGestion

CREATE TABLE PERSONA (
    IDPERSONA INT IDENTITY (1,1) NOT NULL,
    NOMBRE NVARCHAR(50) NOT NULL,
    APELLIDO NVARCHAR(50) NOT NULL,
    ESTADO NVARCHAR(20) NOT NULL,
    PRIMARY KEY (IDPERSONA)
);

CREATE TABLE EMPLEADO (
    IDEMPLEADO INT IDENTITY(1,1) NOT NULL,
    IDPERSONA INT NOT NULL,
    PUESTO NVARCHAR(50) NOT NULL,
    SALARIO MONEY NOT NULL,
    FECHACONTRATACION DATETIME NOT NULL,
    PRIMARY KEY (IDEMPLEADO),
    FOREIGN KEY (IDPERSONA) REFERENCES PERSONA(IDPERSONA)
);

SELECT * FROM PERSONA 

insert into persona values('Pedro' ,'Fernandez','Activo');
insert into persona values('Adrián' ,'Pérez' ,'Activo');
insert into persona values('Belén','González' ,'Activo');
insert into persona values('Ana' ,'Rodríguez' ,'Inactivo');

SELECT * FROM EMPLEADO

INSERT INTO EMPLEADO  VALUES (1, 'Gerente', 5000.00, '2023-01-01');
INSERT INTO EMPLEADO  VALUES (2, 'Asistente', 2500.00, '2023-02-15');
INSERT INTO EMPLEADO  VALUES (3, 'Analista', 3000.00, '2023-03-20');
INSERT INTO EMPLEADO  VALUES (4, 'Secretaria', 2000.00, '2023-04-10');
